/**
 * Checkup calls
 */
CREATE TABLE CheckupCalls
  id UNSIGNED INT NOT NULL AUTO_INCREMENT UNIQUE,
  PRIMARY KEY(id),
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  call_time TIMESTAMP NOT NULL,
  checkup_info_id UNSIGNED INT NOT NULL,
  FOREIGN KEY(checkup_info_id) REFERENCES CheckupInfos(id));
