/**
 * Interview calls 
 */
CREATE TABLE InterviewCalls (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  PRIMARY KEY(id),
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  call_time TIMESTAMP NOT NULL,
  interview_info_id INT UNSIGNED NOT NULL,
  FOREIGN KEY(interview_info_id) REFERENCES Interviews(id));
