CREATE DATABASE CtlDb;

CREATE TABLE CtlDb.Patient(
	id SERIAL,
	PRIMARY KEY(id),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	first_name VARCHAR(30) NOT NULL,
	last_name VARCHAR(30) NOT NULL,
	medical_record_number VARCHAR(30) NOT NULL);

CREATE TABLE CtlDb.PostOpComplications(
	id SERIAL,
	PRIMARY KEY(id),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	value VARCHAR(45) NOT NULL,
	UNIQUE KEY(value));

CREATE TABLE CtlDb.CervicalPainRatings(
	id SERIAL,
	PRIMARY KEY(id),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	neck UNSIGNED INT NOT NULL,
	head_base UNSIGNED INT NOT NULL,
	headaches UNSIGNED INT NOT NULL,
	arm UNSIGNED INT NOT NULL,
	shoulder UNSIGNED INT NOT NULL,
	shoulder_blade UNSIGNED INT NOT NULL);

CREATE TABLE CtlDb.CervicalOrThoraxicPainRatings(
	id SERIAL,
	PRIMARY KEY(id),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	upper_throrax UNSIGNED INT NOT NULL,
	middle_throrax UNSIGNED INT NOT NULL,
	lower_throrax UNSIGNED INT NOT NULL,
	arm UNSIGNED INT NOT NULL,
	shoulder UNSIGNED INT NOT NULL,
	shoulder_blade UNSIGNED INT NOT NULL,
	leg UNSIGNED INT NOT NULL);

CREATE TABLE CtlDb.LumbarPainRatngs(
	id SERIAL,
	PRIMARY KEY(id),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	back UNSIGNED INT NOT NULL,
	leg UNSIGNED INT NOT NULL,
	groin UNSIGNED INT NOT NULL,
	testicular UNSIGNED INT NOT NULL);

